# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b89b0f49394a9fd3503a9b5576bfefa5c2ab128028d9b5be19d9915de989266ba0624c1cb3674b7c364302616b7676e37850e077c57226429efdaae77b6c40e6

test:
  secret_key_base: ff6e5f65e89059f8dbe6e0a3aea996bf86a73da1b1ca45d17f2468db3f7c2569a7001c899396e22cd60cbbb4b2762ceaaba2dc0951fbab30787f00a438d32ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
